# Generated by Django 3.2.12 on 2022-09-25 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appSistemaContable', '0004_alter_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asientos',
                'db_table': 'asiento',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('recibe_saldo', models.BooleanField()),
                ('saldo_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'cuentas',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='TipoPerfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_perfiles',
            },
        ),
        migrations.CreateModel(
            name='PerfilesTareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.ForeignKey(db_column='id_tarea', on_delete=django.db.models.deletion.DO_NOTHING, to='appSistemaContable.tareas')),
                ('id_tipo_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='appSistemaContable.tipoperfiles')),
            ],
            options={
                'db_table': 'perfiles_tareas',
            },
        ),
        migrations.CreateModel(
            name='CuentaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appSistemaContable.asiento')),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appSistemaContable.cuentas')),
            ],
            options={
                'db_table': 'cuenta_asiento',
            },
        ),
    ]
